
/**
THIS FILE IS AUTOGENERATED FROM PYTHON, DO NOT EDIT MANUALLY
*/
export enum EscapementType{
    DEADBEAT = "deadbeat",
    RECOIL = "recoil",
    GRASSHOPPER = "grasshopper",
    NOT_IMPLEMENTED = "None"
}
export let EscapementType_list: EscapementType[] = [EscapementType.DEADBEAT,EscapementType.RECOIL,EscapementType.GRASSHOPPER,EscapementType.NOT_IMPLEMENTED]

export enum GearStyle{
    SOLID = "None",
    ARCS = "HAC",
    CIRCLES = "circles",
    CIRCLES_HOLLOW = "circles_hollow",
    SIMPLE4 = "simple4",
    SIMPLE5 = "simple5",
    SPOKES = "spokes",
    STEAMTRAIN = "steamtrain",
    CARTWHEEL = "cartwheel",
    FLOWER = "flower",
    HONEYCOMB = "honeycomb",
    HONEYCOMB_SMALL = "honeycomb_small",
    SNOWFLAKE = "snowflake",
    CURVES = "curves",
    DIAMONDS = "diamonds"
}
export let GearStyle_list: GearStyle[] = [GearStyle.SOLID,GearStyle.ARCS,GearStyle.CIRCLES,GearStyle.CIRCLES_HOLLOW,GearStyle.SIMPLE4,GearStyle.SIMPLE5,GearStyle.SPOKES,GearStyle.STEAMTRAIN,GearStyle.CARTWHEEL,GearStyle.FLOWER,GearStyle.HONEYCOMB,GearStyle.HONEYCOMB_SMALL,GearStyle.SNOWFLAKE,GearStyle.CURVES,GearStyle.DIAMONDS]

export enum HandStyle{
    SQUARE = "square",
    SIMPLE = "simple",
    SIMPLE_ROUND = "simple_rounded",
    CUCKOO = "cuckoo",
    SPADE = "spade",
    BREGUET = "breguet",
    SYRINGE = "syringe",
    SWORD = "sword",
    CIRCLES = "circles",
    XMAS_TREE = "xmas_tree",
    BAROQUE = "baroque"
}
export let HandStyle_list: HandStyle[] = [HandStyle.SQUARE,HandStyle.SIMPLE,HandStyle.SIMPLE_ROUND,HandStyle.CUCKOO,HandStyle.SPADE,HandStyle.BREGUET,HandStyle.SYRINGE,HandStyle.SWORD,HandStyle.CIRCLES,HandStyle.XMAS_TREE,HandStyle.BAROQUE]

export enum AnchorStyle{
    STRAIGHT = "straight",
    CURVED = "curved",
    CURVED_MATCHING_WHEEL = "curved2"
}
export let AnchorStyle_list: AnchorStyle[] = [AnchorStyle.STRAIGHT,AnchorStyle.CURVED,AnchorStyle.CURVED_MATCHING_WHEEL]

export enum DialStyle{
    LINES_ARC = "lines_arc",
    LINES_RECT = "lines_rect",
    ROMAN = "roman",
    CUCKOO = "cuckoo",
    DOTS = "dots",
    CONCENTRIC_CIRCLES = "concentric_circles"
}
export let DialStyle_list: DialStyle[] = [DialStyle.LINES_ARC,DialStyle.LINES_RECT,DialStyle.ROMAN,DialStyle.CUCKOO,DialStyle.DOTS,DialStyle.CONCENTRIC_CIRCLES]
